-- public.grupo_partida definition

-- Drop table

-- DROP TABLE public.grupo_partida;

CREATE TABLE public.grupo_partida (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	atual bool NULL,
	CONSTRAINT grupo_partida_pkey PRIMARY KEY (id)
);


-- public.jogador definition

-- Drop table

-- DROP TABLE public.jogador;

CREATE TABLE public.jogador (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(50) NOT NULL,
	CONSTRAINT jogador_pkey PRIMARY KEY (id)
);


-- public.jogo definition

-- Drop table

-- DROP TABLE public.jogo;

CREATE TABLE public.jogo (
	id int4 NOT NULL,
	qtd_jogadores int4 NOT NULL,
	qtd_resistencia int4 NOT NULL,
	qtd_espioes int4 NOT NULL,
	CONSTRAINT jogo_pkey PRIMARY KEY (id)
);


-- public.personagem definition

-- Drop table

-- DROP TABLE public.personagem;

CREATE TABLE public.personagem (
	id int4 NOT NULL,	
	descricao varchar(50) NOT NULL,
	ids_info varchar(100) NULL,
	info varchar(50) NULL,
	team varchar(1) NOT NULL,
	CONSTRAINT personagem_pkey PRIMARY KEY (id)
);

CREATE TABLE public.partida (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	atual bool NULL,
	espioes bool NULL,
	resistencia bool NULL,
	id_grupo int4 NULL,
	id_jogo int4 NOT NULL,
	CONSTRAINT partida_pkey PRIMARY KEY (id),
	CONSTRAINT fkilinggtfsf1jo2ver140wp8i5 FOREIGN KEY (id_jogo) REFERENCES public.jogo(id),
	CONSTRAINT fkpnh13of63eh7ng4rque2gs7ar FOREIGN KEY (id_grupo) REFERENCES public.grupo_partida(id)
);


-- public.partida_jogador definition

-- Drop table

-- DROP TABLE public.partida_jogador;

CREATE TABLE public.partida_jogador (
	id_jogador int4 NOT NULL,
	id_partida int4 NOT NULL,
	id_personagem int4 NOT NULL,
	CONSTRAINT partida_jogador_pkey PRIMARY KEY (id_jogador, id_partida),
	CONSTRAINT fkbi9dsrougbxh00tc6fx14yemr FOREIGN KEY (id_partida) REFERENCES public.partida(id),
	CONSTRAINT fki7ynwswuca98fgvckxtama0ac FOREIGN KEY (id_personagem) REFERENCES public.personagem(id),
	CONSTRAINT fkkm2yxc5as3verfqi9f8x7410f FOREIGN KEY (id_jogador) REFERENCES public.jogador(id) ON DELETE CASCADE
);
	
INSERT INTO public.jogador (nome) VALUES
	 ('Victor'),
	 ('Pedro'),
	 ('Maurinho'),
	 ('Glenda'),
	 ('MV'),
	 ('Gabriel'),
	 ('Joanderson'),
	 ('Maria');

INSERT INTO public.personagem (id, descricao, ids_info,info, team) VALUES
	 (1, 'ESPIAO', '1,2,3,4', 'Espiões', 'E'),
	 (2, 'FALSO_COMANDANTE', '1,2,3,4', 'Espiões', 'E'),	 	 
	 (3, 'ASSASSINO', '1,2,3,4', 'Espiões', 'E'),	 
	 (4, 'AGENTE_INVISIVEL', '1,2,3,4', 'Espiões', 'E'),
	 (5, 'GUARDA_COSTAS', '2,6', 'Comadante', 'R'),
	 (6, 'COMANDANTE', '1,2,3', 'Espiões', 'R'),
	 (7, 'RESISTENCIA', NULL, '', 'R');	

	
INSERT INTO public.jogo (id,qtd_jogadores, qtd_resistencia, qtd_espioes) VALUES
	 (1, 5, 3, 2),
	 (2, 6, 4, 2),
	 (3, 7, 4, 3),
	 (4, 8, 5, 3),
	 (5, 9, 6, 3),
	 (6, 10, 6, 4);
	